travis:
  secure:
    BINSTAR_TOKEN: PRwWt3V1j9b6KiOVh+yIZdbbRejtf1TCJMTNKltSkBBpoeqMtxBI4EANngHIpzcuItbKXfWwyjBYuM3vn5yRifXFWppeD0XEkeqlOojAVs0yvVaVapk3FG60B1Hh90SZhpqAsnbs0HjDeEgg6xP2BoBHPb1Qyqy6EZWta8j9urlOORAcF2Vfv7KnteUF+XRO69K1HWPAhyqPFnjLmxz2JyAGu5CMMN8Jh37qrtUfLG6Ou8KSSNijG+w56UkjaDLhoyh0oPOM8fpovO4l8ht054OoTaB4IwhbPmWk/CzGNAAfd6WkRrj8F0FyqLlLbYb+U1hOzx3c/7stB9+Ta+8Fn6uidSVC4n4s5DJ7KIcvh+0PALCCkCrxdmrL5wMraZrT7+ndX0yfT/YhtQRucM5WxjY0yVFbuVSKJg0acPpFJaPGO/hFFFonj356FvZ7bsRs73M4foD+zT7DkgdpPcYNWm4GZoyD0LMP4AVxAO8+M1r66dl+8w4mdj41op5UEb+SB6hRjOq0MwqJy4tZrQ5g2LybzZVasMA9XAOT2BA7EMvH3ERvBxB4spaBUHIDBJQoXlgueZ52YVkJmjmK79IKLPpk8QVeTIoTBr96YiZKoO76ruXxo17Pl8VQF+oZ2J5BoiSAdSiVxh+QXrX9m6XFYcKBAy072V6UVhfL9wpSGXM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
