travis:
  secure:
    BINSTAR_TOKEN: qesFgzL0aRq+T4QfrUcmQon+BtMdQjTX+a3jA/SvDpXKPZdTDZvdWBiVQktB9lJvsY4n/vgBo/aM9//Phu1F3Q0eTuAscTGPbpokBeMwiL+JdZclcTuNklhI3Y6skXfPQtH7M+TZN4bzSc6EJhJqYtF417RugyHYgPc/P7sxGO4TIKiFlxpRhvBX1PlCar5e8geM2SKtf1k6QTjpUL2q4+leRLZPNYlwCExxhIMFat0wVLJD1NRdZEWKkWznfGwtZnMMPGM8WaHovnCXq8P/hBaqwTdC6VuPh/8A2Q0kq7EsDl7eKVPDSyitW8eEmT8DVKaL/VnLZYknWFcivcFbV2/e3BvB8N1Kw9GDjJku2QqOALbzLG4r9Gnn+3bVYHt6TtMiE1Pz6huMlczmgBybu65PYhj4yJrjyFD3832swioPam5h48mOxfeoXvxjyQ+iOTJE3vXu65ERnjgP2PuZuQ5YItn00L+0dzI7XFFkj4vCtYnzp9iIwx4uj7i1v359srG5/MhepXqwn9ZX+t/twwOZUT0WBSF0bqaM5rw7/jh0SpZQeFcxGczllC8oZfacClTVD5FGFTbjkzIprqTLzzr741JiEm3a2dyWJWiGQo5ifMHaG9CQ9rrE4LiwFjuqNGr0+qXkttfAorzH3oRtuRwDwD4Yc9ElYj1YbzJvLO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
